package authorgroups

import "github.com/claucambra/commit-analysis-tool/pkg/common"

const testCommitsFile = "../../../test/data/log.txt"

const testNumAuthors = 247
const testNumInsertions = 628508
const testNumDeletions = 430104
const testNumGroupAuthors = 16
const testGroupName = "VideoLAN"
const testGroupDomain = "videolan.org"
const testGroupInsertions = 44917
const testGroupDeletions = 32959
const testOtherName = fallbackGroupName
const testNumOtherAuthors = 231
const testOtherInsertions = 583591
const testOtherDeletions = 397145

func testEmailGroups() map[string][]string {
	return map[string][]string{
		testGroupName: {testGroupDomain},
	}
}

func testGroupAuthors() common.EmailSet {
	return common.EmailSet{
		"40552-sjwaddy@users.noreply.code.videolan.org": true,
		"dfuhrmann@videolan.org":                        true,
		"erwan10@videolan.org":                          true,
		"fkuehne@videolan.org":                          true,
		"funman@videolan.org":                           true,
		"garf@videolan.org":                             true,
		"git@videolan.org":                              true,
		"ileoo@videolan.org":                            true,
		"jb@videolan.org":                               true,
		"magsoft@videolan.org":                          true,
		"robux@videolan.org":                            true,
		"salah@videolan.org":                            true,
		"thresh@videolan.org":                           true,
		"tmatth@videolan.org":                           true,
		"typx@videolan.org":                             true,
		"videolan@videolan.org":                         true,
	}
}

func testOtherAuthors() common.EmailSet {
	return common.EmailSet{
		"sramacher@debian.org":                                 true,
		"my_aashish@live.in":                                   true,
		"jjm_223@hotmail.com":                                  true,
		"rom1v@videolabs.io":                                   true,
		"vagrant@reproducible-builds.org":                      true,
		"13hurdw@gmail.com":                                    true,
		"andrew@crossbowffs.com":                               true,
		"AWilcox@Wilcox-Tech.com":                              true,
		"jnqnfe@gmail.com":                                     true,
		"EwoutterHoeven@live.nl":                               true,
		"filip@atch.se":                                        true,
		"vittorio.giovara@gmail.com":                           true,
		"lamisedaxeh@yahoo.com":                                true,
		"kd913@ic.ac.uk":                                       true,
		"appdev@chernyakov.com":                                true,
		"stefan.bruens@rwth-aachen.de":                         true,
		"robux4@ycbcr.xyz":                                     true,
		"lu_zero@gentoo.org":                                   true,
		"iulian.onofrei@yahoo.com":                             true,
		"quentin.chateau@deepskycorp.com":                      true,
		"Abeltesfaye45@gmail.com":                              true,
		"ssdoria@gmail.com":                                    true,
		"johnddx@hotmail.com":                                  true,
		"erythros@gmail.com":                                   true,
		"dev@maelkervella.eu":                                  true,
		"umxprime@videolabs.io":                                true,
		"E.M.terHoeven@student.tudelft.nl":                     true,
		"bunjee@omega.gg":                                      true,
		"yann@l0chet.fr":                                       true,
		"e.m.terhoeven@student.tudelft.nl":                     true,
		"zebob.m@gmail.com":                                    true,
		"lsegretin.contrib@gmail.com":                          true,
		"meskobalazs@gmail.com":                                true,
		"mehdi@videolabs.io":                                   true,
		"abeltesfaye45@gmail.com":                              true,
		"dev.asenat@posteo.net":                                true,
		"johanneskauffmann@hotmail.com":                        true,
		"pico.dev@gmail.com":                                   true,
		"chishtiawais511@gmail.com":                            true,
		"phintuka@gmail.com":                                   true,
		"thierry@ordissimo.com":                                true,
		"psplob@gmail.com":                                     true,
		"loiret.d@gmail.com":                                   true,
		"hechenrui123@gmail.com":                               true,
		"jbelloncastro@gmail.com":                              true,
		"lionel.g.landwerlin@intel.com":                        true,
		"jonas.knoell@googlemail.com":                          true,
		"me@jailuthra.in":                                      true,
		"nicolas.lequec@gmail.com":                             true,
		"bubu@mikan.io":                                        true,
		"advaitgupta@ymail.com":                                true,
		"kayazeren@gmail.com":                                  true,
		"jc@kynesim.co.uk":                                     true,
		"komh@chollian.net":                                    true,
		"yohann.danello@gmail.com":                             true,
		"rohan17089@iiitd.ac.in":                               true,
		"amar_s1414@hotmail.com":                               true,
		"huangjie@uniontech.com":                               true,
		"tanguy.dubroca@lse.epita.fr":                          true,
		"khalid.masum.92@gmail.com":                            true,
		"rofferom@gmail.com":                                   true,
		"mromanov@elvees.com":                                  true,
		"contact@olivieraubert.net":                            true,
		"yuri_sevatz@hotmail.com":                              true,
		"pierre@videolabs.io":                                  true,
		"aymericguillien.pro@gmail.com":                        true,
		"fuzun54@outlook.com":                                  true,
		"lucenticus@gmail.com":                                 true,
		"sebastian@centricular.com":                            true,
		"ajanni@videolabs.io":                                  true,
		"amanna1041@gmail.com":                                 true,
		"turner.craig@gmail.com":                               true,
		"marek.belesciak@lunar.sk":                             true,
		"fcvlcdev@free.fr":                                     true,
		"boxerab@gmail.com":                                    true,
		"mwy-cpjbvr@the-youngs.org":                            true,
		"podnety@mojepreklady.net":                             true,
		"robux4@videolabs.io":                                  true,
		"melhiors14@gmail.com":                                 true,
		"cwendling@hypra.fr":                                   true,
		"mohitmarathe23@gmail.com":                             true,
		"roland.bewick@gmail.com":                              true,
		"tjanand@usc.edu":                                      true,
		"russell@shotover.com":                                 true,
		"git@haasn.dev":                                        true,
		"janboe.ye@outlook.com":                                true,
		"dannym@scratchpost.org":                               true,
		"shkshk.90@gmail.com":                                  true,
		"alexandre.janniaux@gmail.com":                         true,
		"julien.montant@gmail.com":                             true,
		"blake@haydon.dev":                                     true,
		"vibhoothiiaanand@gmail.com":                           true,
		"guptaprince8832@gmail.com":                            true,
		"zouya@uniontech.com":                                  true,
		"jill@videolabs.io":                                    true,
		"vvaakshay@gmail.com":                                  true,
		"ele7enxxh@gmail.com":                                  true,
		"zorurione@gmail.com":                                  true,
		"Nicolas.Le_Quec@bordeaux-inp.fr":                      true,
		"anton_r_3@hotmail.com":                                true,
		"rdiouskine@haivision.com":                             true,
		"logiconcepts819@gmail.com":                            true,
		"git_78nfp05yca8p0nw7at849pbahfc56w39p@protonmail.com": true,
		"lukas.bergdoll@gmail.com":                             true,
		"matmaul@gmail.com":                                    true,
		"andriykopanytsia@gmail.com":                           true,
		"lyubomirv@abv.bg":                                     true,
		"iam@valdikss.org.ru":                                  true,
		"kartikohri13@gmail.com":                               true,
		"etienne.brateau@gmail.com":                            true,
		"phil@zankapfel.net":                                   true,
		"quentin.chateau@gmail.com":                            true,
		"wzc782970009@gmail.com":                               true,
		"marc@darkdust.net":                                    true,
		"kohli.sagar2@gmail.com":                               true,
		"dima@doty.ru":                                         true,
		"jeff@jeffreyknockel.com":                              true,
		"mjakubowski@gmail.com":                                true,
		"thebarshablog@gmail.com":                              true,
		"xqq@xqq.im":                                           true,
		"developer@claudiocambra.com":                          true,
		"leon.vitanos@gmail.com":                               true,
		"adamjleung123@gmail.com":                              true,
		"nicholas.h.briggs@gmail.com":                          true,
		"maite.guix@me.com":                                    true,
		"daniel.charles@intel.com":                             true,
		"jluedtk@jci.com":                                      true,
		"vedantnayak2@gmail.com":                               true,
		"miguelfrego@gmail.com":                                true,
		"xnagytibor@protonmail.com":                            true,
		"onemda@gmail.com":                                     true,
		"mmeisson@outlook.fr":                                  true,
		"epirat07@gmail.com":                                   true,
		"delthas@dille.cc":                                     true,
		"olivier.crete@collabora.com":                          true,
		"mail@ashu.io":                                         true,
		"a.koverninsky@gmail.com":                              true,
		"oneric@oneric.de":                                     true,
		"daksh17336@iiitd.ac.in":                               true,
		"finkel2804@gmail.com":                                 true,
		"martin@martin.st":                                     true,
		"ofourdan@redhat.com":                                  true,
		"attekett@gmail.com":                                   true,
		"mail@michael-kaufmann.ch":                             true,
		"nic.da.zunk@gmail.com":                                true,
		"king7532@mac.com":                                     true,
		"ferdnyc@gmail.com":                                    true,
		"val.zapod.vz@gmail.com":                               true,
		"mitch.capper@gmail.com":                               true,
		"7damian7@onet.eu":                                     true,
		"17aakashsingh1999@gmail.com":                          true,
		"daniel.glaas@freenet.de":                              true,
		"remi@remlab.net":                                      true,
		"mark.lee@capricasoftware.co.uk":                       true,
		"katolaz@freaknet.org":                                 true,
		"shaleen@jain.sh":                                      true,
		"luizfrdasilva@gmail.com":                              true,
		"dottedmag@dottedmag.net":                              true,
		"software@froissart.eu":                                true,
		"martin@videolabs.io":                                  true,
		"jeremy.vignelles@gmail.com":                           true,
		"Aleksey.Kuznetsov@noveogroup.com":                     true,
		"zhilizhao@tencent.com":                                true,
		"michtrz@gmail.com":                                    true,
		"emmanuel.nicolet@gmail.com":                           true,
		"david.nicolson@gmail.com":                             true,
		"gudvinr@gmail.com":                                    true,
		"nurupo.contributions@gmail.com":                       true,
		"daniel.ashkenazi@gmail.com":                           true,
		"louis@videolabs.io":                                   true,
		"vinx.reale@gmail.com":                                 true,
		"janne-vlc@jannau.net":                                 true,
		"linkfanel@yahoo.fr":                                   true,
		"mail@asciiwolf.com":                                   true,
		"kerrick@kerrickstaley.com":                            true,
		"dasistdumm2+vlc@gmail.com":                            true,
		"sirotaalon@gmail.com":                                 true,
		"fabrice@bellet.info":                                  true,
		"arnold.marko@gmail.com":                               true,
		"dmitriy.matveichev@qligent.com":                       true,
		"komh78@gmail.com":                                     true,
		"i.know.kungfu@outlook.com":                            true,
		"quinkblack@foxmail.com":                               true,
		"dheitmueller@ltnglobal.com":                           true,
		"marcoslansgarza@gmail.com":                            true,
		"loic@videolabs.io":                                    true,
		"thomas@gllm.fr":                                       true,
		"hugo@beauzee.fr":                                      true,
		"hukeyue@hotmail.com":                                  true,
		"farid.hammane@gmail.com":                              true,
		"ssbssa@yahoo.de":                                      true,
		"christian.l.christiansen@gmail.com":                   true,
		"aaron.boxer@collabora.com":                            true,
		"thomasderocker@outlook.com":                           true,
		"dima.buzdyk@gmail.com":                                true,
		"kde@privat.broulik.de":                                true,
		"06needhamt@gmail.com":                                 true,
		"sergio@ammirata.net":                                  true,
		"juhapekka.heikkila@gmail.com":                         true,
		"295993170@qq.com":                                     true,
		"rsatom@gmail.com":                                     true,
		"rsbultje@gmail.com":                                   true,
		"victorien.lecouviour.tuffet@gmail.com":                true,
		"ilya.yanok@gmail.com":                                 true,
		"benjamin.arnaud@videolabs.io":                         true,
		"akrug@arcor.de":                                       true,
		"william1.ung@epitech.eu":                              true,
		"typx@dinauz.org":                                      true,
		"nathbappai@gmail.com":                                 true,
		"brad@comstyle.com":                                    true,
		"andrewkhon98@gmail.com":                               true,
		"me@martinfinkel.com":                                  true,
		"lukas@positive.security":                              true,
		"mail@lucaswerkmeister.de":                             true,
		"hugokarvalho@hotmail.com":                             true,
		"vikram.fugro@gmail.com":                               true,
		"bwiedemann@suse.de":                                   true,
		"sh.yaron@gmail.com":                                   true,
		"fenngtun@gmail.com":                                   true,
		"gseanmcg@gmail.com":                                   true,
		"mehdisabwat@gmail.com":                                true,
		"antonio.larrosa@gmail.com":                            true,
		"git@haasn.xyz":                                        true,
		"natalie.landsberg97@gmail.com":                        true,
		"fumio.n6a@gmail.com":                                  true,
		"hparnica@gmail.com":                                   true,
		"will.newton@gmail.com":                                true,
		"i@hexchain.org":                                       true,
		"geoffrey.metais@gmail.com":                            true,
		"claudio.cambra@gmail.com":                             true,
		"johan.gunnarsson@gmail.com":                           true,
	}
}

func testGroupYearlyLineChanges() common.YearlyLineChangeMap {
	return common.YearlyLineChangeMap{
		2016: {NumInsertions: 13, NumDeletions: 1},
		2018: {NumInsertions: 4115, NumDeletions: 1555},
		2019: {NumInsertions: 35659, NumDeletions: 26361},
		2020: {NumInsertions: 2783, NumDeletions: 1018},
		2021: {NumInsertions: 1267, NumDeletions: 1405},
		2022: {NumInsertions: 668, NumDeletions: 2289},
		2023: {NumInsertions: 412, NumDeletions: 330},
	}
}

func testOtherYearlyLineChanges() common.YearlyLineChangeMap {
	return common.YearlyLineChangeMap{
		1970: {NumInsertions: 318, NumDeletions: 357},
		2010: {NumInsertions: 1, NumDeletions: 16},
		2014: {NumInsertions: 491, NumDeletions: 2},
		2016: {NumInsertions: 4966, NumDeletions: 368},
		2017: {NumInsertions: 111, NumDeletions: 69},
		2018: {NumInsertions: 81696, NumDeletions: 33055},
		2019: {NumInsertions: 133643, NumDeletions: 112960},
		2020: {NumInsertions: 125639, NumDeletions: 80658},
		2021: {NumInsertions: 98422, NumDeletions: 64119},
		2022: {NumInsertions: 98441, NumDeletions: 80241},
		2023: {NumInsertions: 39863, NumDeletions: 25300},
	}
}

func testGroupYearlyAuthors() common.YearlyEmailMap {
	return common.YearlyEmailMap{
		2016: {"tmatth@videolan.org": true},
		2018: {
			"dfuhrmann@videolan.org": true,
			"erwan10@videolan.org":   true,
			"fkuehne@videolan.org":   true,
			"funman@videolan.org":    true,
			"ileoo@videolan.org":     true,
			"jb@videolan.org":        true,
			"magsoft@videolan.org":   true,
			"salah@videolan.org":     true,
			"thresh@videolan.org":    true,
			"tmatth@videolan.org":    true,
			"typx@videolan.org":      true,
		},
		2019: {
			"dfuhrmann@videolan.org": true,
			"erwan10@videolan.org":   true,
			"fkuehne@videolan.org":   true,
			"garf@videolan.org":      true,
			"ileoo@videolan.org":     true,
			"jb@videolan.org":        true,
			"magsoft@videolan.org":   true,
			"thresh@videolan.org":    true,
			"tmatth@videolan.org":    true,
			"typx@videolan.org":      true,
		},
		2020: {
			"dfuhrmann@videolan.org": true,
			"erwan10@videolan.org":   true,
			"fkuehne@videolan.org":   true,
			"git@videolan.org":       true,
			"jb@videolan.org":        true,
			"thresh@videolan.org":    true,
			"tmatth@videolan.org":    true,
			"videolan@videolan.org":  true,
		},
		2021: {
			"40552-sjwaddy@users.noreply.code.videolan.org": true,
			"dfuhrmann@videolan.org":                        true,
			"fkuehne@videolan.org":                          true,
			"ileoo@videolan.org":                            true,
			"jb@videolan.org":                               true,
			"salah@videolan.org":                            true,
			"thresh@videolan.org":                           true,
			"tmatth@videolan.org":                           true,
		},
		2022: {
			"dfuhrmann@videolan.org": true,
			"fkuehne@videolan.org":   true,
			"jb@videolan.org":        true,
			"robux@videolan.org":     true,
			"tmatth@videolan.org":    true,
		},
		2023: {
			"dfuhrmann@videolan.org": true,
			"fkuehne@videolan.org":   true,
			"garf@videolan.org":      true,
			"ileoo@videolan.org":     true,
			"jb@videolan.org":        true,
			"tmatth@videolan.org":    true,
		},
	}
}

func testOtherYearlyAuthors() common.YearlyEmailMap {
	return common.YearlyEmailMap{
		1970: {"robux4@ycbcr.xyz": true},
		2010: {"remi@remlab.net": true},
		2014: {"remi@remlab.net": true},
		2016: {
			"fcvlcdev@free.fr":     true,
			"janne-vlc@jannau.net": true,
			"robux4@videolabs.io":  true,
		},
		2017: {
			"etienne.brateau@gmail.com": true,
			"fcvlcdev@free.fr":          true,
			"jnqnfe@gmail.com":          true,
		},
		2018: {
			"AWilcox@Wilcox-Tech.com":               true,
			"alexandre.janniaux@gmail.com":          true,
			"bubu@mikan.io":                         true,
			"contact@olivieraubert.net":             true,
			"daksh17336@iiitd.ac.in":                true,
			"dheitmueller@ltnglobal.com":            true,
			"epirat07@gmail.com":                    true,
			"erythros@gmail.com":                    true,
			"fcvlcdev@free.fr":                      true,
			"filip@atch.se":                         true,
			"geoffrey.metais@gmail.com":             true,
			"git@haasn.xyz":                         true,
			"hparnica@gmail.com":                    true,
			"hugo@beauzee.fr":                       true,
			"jnqnfe@gmail.com":                      true,
			"juhapekka.heikkila@gmail.com":          true,
			"kd913@ic.ac.uk":                        true,
			"komh78@gmail.com":                      true,
			"linkfanel@yahoo.fr":                    true,
			"lukas.bergdoll@gmail.com":              true,
			"mail@lucaswerkmeister.de":              true,
			"martin@martin.st":                      true,
			"me@martinfinkel.com":                   true,
			"nicholas.h.briggs@gmail.com":           true,
			"ofourdan@redhat.com":                   true,
			"olivier.crete@collabora.com":           true,
			"onemda@gmail.com":                      true,
			"pierre@videolabs.io":                   true,
			"quinkblack@foxmail.com":                true,
			"rdiouskine@haivision.com":              true,
			"remi@remlab.net":                       true,
			"robux4@ycbcr.xyz":                      true,
			"rom1v@videolabs.io":                    true,
			"sergio@ammirata.net":                   true,
			"shaleen@jain.sh":                       true,
			"ssbssa@yahoo.de":                       true,
			"thomas@gllm.fr":                        true,
			"victorien.lecouviour.tuffet@gmail.com": true,
			"vikram.fugro@gmail.com":                true,
			"william1.ung@epitech.eu":               true,
		},
		2019: {
			"06needhamt@gmail.com":                  true,
			"17aakashsingh1999@gmail.com":           true,
			"Abeltesfaye45@gmail.com":               true,
			"E.M.terHoeven@student.tudelft.nl":      true,
			"EwoutterHoeven@live.nl":                true,
			"a.koverninsky@gmail.com":               true,
			"aaron.boxer@collabora.com":             true,
			"abeltesfaye45@gmail.com":               true,
			"ajanni@videolabs.io":                   true,
			"alexandre.janniaux@gmail.com":          true,
			"antonio.larrosa@gmail.com":             true,
			"attekett@gmail.com":                    true,
			"boxerab@gmail.com":                     true,
			"chishtiawais511@gmail.com":             true,
			"contact@olivieraubert.net":             true,
			"daniel.charles@intel.com":              true,
			"dannym@scratchpost.org":                true,
			"delthas@dille.cc":                      true,
			"dev@maelkervella.eu":                   true,
			"dheitmueller@ltnglobal.com":            true,
			"dottedmag@dottedmag.net":               true,
			"ele7enxxh@gmail.com":                   true,
			"emmanuel.nicolet@gmail.com":            true,
			"epirat07@gmail.com":                    true,
			"fabrice@bellet.info":                   true,
			"fcvlcdev@free.fr":                      true,
			"ferdnyc@gmail.com":                     true,
			"finkel2804@gmail.com":                  true,
			"git@haasn.xyz":                         true,
			"gseanmcg@gmail.com":                    true,
			"hechenrui123@gmail.com":                true,
			"hugo@beauzee.fr":                       true,
			"iam@valdikss.org.ru":                   true,
			"janne-vlc@jannau.net":                  true,
			"jnqnfe@gmail.com":                      true,
			"johan.gunnarsson@gmail.com":            true,
			"kde@privat.broulik.de":                 true,
			"kohli.sagar2@gmail.com":                true,
			"komh78@gmail.com":                      true,
			"komh@chollian.net":                     true,
			"linkfanel@yahoo.fr":                    true,
			"loiret.d@gmail.com":                    true,
			"lsegretin.contrib@gmail.com":           true,
			"lu_zero@gentoo.org":                    true,
			"luizfrdasilva@gmail.com":               true,
			"marek.belesciak@lunar.sk":              true,
			"martin@martin.st":                      true,
			"matmaul@gmail.com":                     true,
			"me@jailuthra.in":                       true,
			"mehdisabwat@gmail.com":                 true,
			"mmeisson@outlook.fr":                   true,
			"mwy-cpjbvr@the-youngs.org":             true,
			"natalie.landsberg97@gmail.com":         true,
			"onemda@gmail.com":                      true,
			"phintuka@gmail.com":                    true,
			"pierre@videolabs.io":                   true,
			"quentin.chateau@gmail.com":             true,
			"quinkblack@foxmail.com":                true,
			"remi@remlab.net":                       true,
			"robux4@ycbcr.xyz":                      true,
			"rohan17089@iiitd.ac.in":                true,
			"roland.bewick@gmail.com":               true,
			"rom1v@videolabs.io":                    true,
			"rsatom@gmail.com":                      true,
			"sergio@ammirata.net":                   true,
			"shaleen@jain.sh":                       true,
			"software@froissart.eu":                 true,
			"stefan.bruens@rwth-aachen.de":          true,
			"thomas@gllm.fr":                        true,
			"vibhoothiiaanand@gmail.com":            true,
			"victorien.lecouviour.tuffet@gmail.com": true,
			"vittorio.giovara@gmail.com":            true,
			"will.newton@gmail.com":                 true,
			"zhilizhao@tencent.com":                 true,
			"zorurione@gmail.com":                   true,
		},
		2020: {
			"Aleksey.Kuznetsov@noveogroup.com": true,
			"ajanni@videolabs.io":              true,
			"akrug@arcor.de":                   true,
			"amar_s1414@hotmail.com":           true,
			"andriykopanytsia@gmail.com":       true,
			"anton_r_3@hotmail.com":            true,
			"arnold.marko@gmail.com":           true,
			"bwiedemann@suse.de":               true,
			"daniel.glaas@freenet.de":          true,
			"dev.asenat@posteo.net":            true,
			"dima.buzdyk@gmail.com":            true,
			"epirat07@gmail.com":               true,
			"farid.hammane@gmail.com":          true,
			"fcvlcdev@free.fr":                 true,
			"finkel2804@gmail.com":             true,
			"fumio.n6a@gmail.com":              true,
			"fuzun54@outlook.com":              true,
			"git@haasn.xyz":                    true,
			"gseanmcg@gmail.com":               true,
			"guptaprince8832@gmail.com":        true,
			"hugo@beauzee.fr":                  true,
			"hugokarvalho@hotmail.com":         true,
			"ilya.yanok@gmail.com":             true,
			"iulian.onofrei@yahoo.com":         true,
			"janboe.ye@outlook.com":            true,
			"jc@kynesim.co.uk":                 true,
			"jnqnfe@gmail.com":                 true,
			"jonas.knoell@googlemail.com":      true,
			"julien.montant@gmail.com":         true,
			"kartikohri13@gmail.com":           true,
			"katolaz@freaknet.org":             true,
			"kayazeren@gmail.com":              true,
			"lamisedaxeh@yahoo.com":            true,
			"linkfanel@yahoo.fr":               true,
			"lionel.g.landwerlin@intel.com":    true,
			"logiconcepts819@gmail.com":        true,
			"louis@videolabs.io":               true,
			"lyubomirv@abv.bg":                 true,
			"maite.guix@me.com":                true,
			"marc@darkdust.net":                true,
			"marcoslansgarza@gmail.com":        true,
			"mark.lee@capricasoftware.co.uk":   true,
			"martin@martin.st":                 true,
			"martin@videolabs.io":              true,
			"me@martinfinkel.com":              true,
			"mehdi@videolabs.io":               true,
			"mehdisabwat@gmail.com":            true,
			"melhiors14@gmail.com":             true,
			"meskobalazs@gmail.com":            true,
			"michtrz@gmail.com":                true,
			"nathbappai@gmail.com":             true,
			"phintuka@gmail.com":               true,
			"pico.dev@gmail.com":               true,
			"pierre@videolabs.io":              true,
			"podnety@mojepreklady.net":         true,
			"psplob@gmail.com":                 true,
			"quentin.chateau@deepskycorp.com":  true,
			"quinkblack@foxmail.com":           true,
			"remi@remlab.net":                  true,
			"robux4@ycbcr.xyz":                 true,
			"rom1v@videolabs.io":               true,
			"sergio@ammirata.net":              true,
			"sh.yaron@gmail.com":               true,
			"sirotaalon@gmail.com":             true,
			"sramacher@debian.org":             true,
			"ssdoria@gmail.com":                true,
			"tanguy.dubroca@lse.epita.fr":      true,
			"thomas@gllm.fr":                   true,
			"thomasderocker@outlook.com":       true,
			"vedantnayak2@gmail.com":           true,
			"vibhoothiiaanand@gmail.com":       true,
			"vikram.fugro@gmail.com":           true,
			"vinx.reale@gmail.com":             true,
			"vvaakshay@gmail.com":              true,
			"yohann.danello@gmail.com":         true,
			"yuri_sevatz@hotmail.com":          true,
			"zebob.m@gmail.com":                true,
		},
		2021: {
			"Aleksey.Kuznetsov@noveogroup.com":   true,
			"Nicolas.Le_Quec@bordeaux-inp.fr":    true,
			"adamjleung123@gmail.com":            true,
			"advaitgupta@ymail.com":              true,
			"ajanni@videolabs.io":                true,
			"alexandre.janniaux@gmail.com":       true,
			"benjamin.arnaud@videolabs.io":       true,
			"blake@haydon.dev":                   true,
			"brad@comstyle.com":                  true,
			"christian.l.christiansen@gmail.com": true,
			"contact@olivieraubert.net":          true,
			"cwendling@hypra.fr":                 true,
			"daniel.ashkenazi@gmail.com":         true,
			"dasistdumm2+vlc@gmail.com":          true,
			"david.nicolson@gmail.com":           true,
			"dev.asenat@posteo.net":              true,
			"dima@doty.ru":                       true,
			"e.m.terhoeven@student.tudelft.nl":   true,
			"epirat07@gmail.com":                 true,
			"fcvlcdev@free.fr":                   true,
			"fuzun54@outlook.com":                true,
			"git@haasn.dev":                      true,
			"git@haasn.xyz":                      true,
			"gseanmcg@gmail.com":                 true,
			"gudvinr@gmail.com":                  true,
			"guptaprince8832@gmail.com":          true,
			"huangjie@uniontech.com":             true,
			"hugo@beauzee.fr":                    true,
			"i.know.kungfu@outlook.com":          true,
			"jeremy.vignelles@gmail.com":         true,
			"jnqnfe@gmail.com":                   true,
			"johanneskauffmann@hotmail.com":      true,
			"komh78@gmail.com":                   true,
			"komh@chollian.net":                  true,
			"linkfanel@yahoo.fr":                 true,
			"lukas@positive.security":            true,
			"mail@ashu.io":                       true,
			"mail@michael-kaufmann.ch":           true,
			"mark.lee@capricasoftware.co.uk":     true,
			"martin@martin.st":                   true,
			"martin@videolabs.io":                true,
			"me@martinfinkel.com":                true,
			"mehdi@videolabs.io":                 true,
			"mehdisabwat@gmail.com":              true,
			"mitch.capper@gmail.com":             true,
			"my_aashish@live.in":                 true,
			"natalie.landsberg97@gmail.com":      true,
			"nicolas.lequec@gmail.com":           true,
			"phintuka@gmail.com":                 true,
			"pierre@videolabs.io":                true,
			"quinkblack@foxmail.com":             true,
			"remi@remlab.net":                    true,
			"robux4@ycbcr.xyz":                   true,
			"rom1v@videolabs.io":                 true,
			"sergio@ammirata.net":                true,
			"sh.yaron@gmail.com":                 true,
			"shkshk.90@gmail.com":                true,
			"tanguy.dubroca@lse.epita.fr":        true,
			"thomas@gllm.fr":                     true,
			"turner.craig@gmail.com":             true,
			"vagrant@reproducible-builds.org":    true,
			"val.zapod.vz@gmail.com":             true,
			"vedantnayak2@gmail.com":             true,
			"wzc782970009@gmail.com":             true,
			"xnagytibor@protonmail.com":          true,
			"zhilizhao@tencent.com":              true,
			"zouya@uniontech.com":                true,
		},
		2022: {
			"13hurdw@gmail.com":              true,
			"295993170@qq.com":               true,
			"ajanni@videolabs.io":            true,
			"appdev@chernyakov.com":          true,
			"aymericguillien.pro@gmail.com":  true,
			"benjamin.arnaud@videolabs.io":   true,
			"brad@comstyle.com":              true,
			"claudio.cambra@gmail.com":       true,
			"david.nicolson@gmail.com":       true,
			"dev.asenat@posteo.net":          true,
			"developer@claudiocambra.com":    true,
			"epirat07@gmail.com":             true,
			"fcvlcdev@free.fr":               true,
			"fenngtun@gmail.com":             true,
			"fuzun54@outlook.com":            true,
			"git@haasn.dev":                  true,
			"gseanmcg@gmail.com":             true,
			"guptaprince8832@gmail.com":      true,
			"hugo@beauzee.fr":                true,
			"i@hexchain.org":                 true,
			"jeff@jeffreyknockel.com":        true,
			"jill@videolabs.io":              true,
			"jjm_223@hotmail.com":            true,
			"jluedtk@jci.com":                true,
			"jnqnfe@gmail.com":               true,
			"johanneskauffmann@hotmail.com":  true,
			"king7532@mac.com":               true,
			"komh@chollian.net":              true,
			"leon.vitanos@gmail.com":         true,
			"linkfanel@yahoo.fr":             true,
			"louis@videolabs.io":             true,
			"lucenticus@gmail.com":           true,
			"mail@asciiwolf.com":             true,
			"mark.lee@capricasoftware.co.uk": true,
			"martin@martin.st":               true,
			"mehdi@videolabs.io":             true,
			"mehdisabwat@gmail.com":          true,
			"miguelfrego@gmail.com":          true,
			"mjakubowski@gmail.com":          true,
			"mromanov@elvees.com":            true,
			"nurupo.contributions@gmail.com": true,
			"oneric@oneric.de":               true,
			"phil@zankapfel.net":             true,
			"pierre@videolabs.io":            true,
			"quinkblack@foxmail.com":         true,
			"remi@remlab.net":                true,
			"robux4@ycbcr.xyz":               true,
			"rofferom@gmail.com":             true,
			"rom1v@videolabs.io":             true,
			"rsbultje@gmail.com":             true,
			"thierry@ordissimo.com":          true,
			"thomas@gllm.fr":                 true,
			"tjanand@usc.edu":                true,
			"typx@dinauz.org":                true,
			"umxprime@videolabs.io":          true,
			"xqq@xqq.im":                     true,
			"yann@l0chet.fr":                 true,
			"zhilizhao@tencent.com":          true,
		},
		2023: {
			"7damian7@onet.eu":                                     true,
			"ajanni@videolabs.io":                                  true,
			"amanna1041@gmail.com":                                 true,
			"andrew@crossbowffs.com":                               true,
			"andrewkhon98@gmail.com":                               true,
			"benjamin.arnaud@videolabs.io":                         true,
			"bunjee@omega.gg":                                      true,
			"dev.asenat@posteo.net":                                true,
			"developer@claudiocambra.com":                          true,
			"dmitriy.matveichev@qligent.com":                       true,
			"epirat07@gmail.com":                                   true,
			"fcvlcdev@free.fr":                                     true,
			"ferdnyc@gmail.com":                                    true,
			"fuzun54@outlook.com":                                  true,
			"git@haasn.dev":                                        true,
			"git_78nfp05yca8p0nw7at849pbahfc56w39p@protonmail.com": true,
			"gseanmcg@gmail.com":                                   true,
			"guptaprince8832@gmail.com":                            true,
			"hukeyue@hotmail.com":                                  true,
			"jbelloncastro@gmail.com":                              true,
			"johanneskauffmann@hotmail.com":                        true,
			"johnddx@hotmail.com":                                  true,
			"kerrick@kerrickstaley.com":                            true,
			"khalid.masum.92@gmail.com":                            true,
			"komh@chollian.net":                                    true,
			"leon.vitanos@gmail.com":                               true,
			"linkfanel@yahoo.fr":                                   true,
			"loic@videolabs.io":                                    true,
			"martin@martin.st":                                     true,
			"mohitmarathe23@gmail.com":                             true,
			"nic.da.zunk@gmail.com":                                true,
			"nurupo.contributions@gmail.com":                       true,
			"pierre@videolabs.io":                                  true,
			"quinkblack@foxmail.com":                               true,
			"remi@remlab.net":                                      true,
			"robux4@ycbcr.xyz":                                     true,
			"rom1v@videolabs.io":                                   true,
			"russell@shotover.com":                                 true,
			"sebastian@centricular.com":                            true,
			"thebarshablog@gmail.com":                              true,
			"thomas@gllm.fr":                                       true,
			"umxprime@videolabs.io":                                true,
			"yann@l0chet.fr":                                       true,
		},
	}
}

func testGroupData() *GroupData {
	return &GroupData{
		GroupName: testGroupName,
		Authors:   testGroupAuthors(),
		LineChanges: &common.LineChanges{
			NumInsertions: testGroupInsertions,
			NumDeletions:  testGroupDeletions,
		},
		YearlyLineChanges: testGroupYearlyLineChanges(),
		YearlyAuthors:     testGroupYearlyAuthors(),
		AuthorsPercent:    (float32(testNumGroupAuthors) / float32(testNumAuthors)) * 100,
		InsertionsPercent: (float32(testGroupInsertions) / float32(testNumInsertions)) * 100,
		DeletionsPercent:  (float32(testGroupDeletions) / float32(testNumDeletions)) * 100,
	}
}

func testUnknownGroupData() *GroupData {
	return &GroupData{
		GroupName: testOtherName,
		Authors:   testOtherAuthors(),
		LineChanges: &common.LineChanges{
			NumInsertions: testOtherInsertions,
			NumDeletions:  testOtherDeletions,
		},
		YearlyLineChanges: testOtherYearlyLineChanges(),
		YearlyAuthors:     testOtherYearlyAuthors(),
		AuthorsPercent:    (float32(testNumOtherAuthors) / float32(testNumAuthors)) * 100,
		InsertionsPercent: (float32(testOtherInsertions) / float32(testNumInsertions)) * 100,
		DeletionsPercent:  (float32(testOtherDeletions) / float32(testNumDeletions)) * 100,
	}
}
